title: Princeton Geophysics
author: Princeton Geophysics
description: Collection of docs and tutorials written by members of the Princeton Geophysics group.
permalink: pretty
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
toc:
  enabled: true
  h_min: 1
  h_max: 4
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
social-network-links:
  email: "lsawade@princeton.edu"
  # rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: lsawade

url-pretty: "Princeton Geophysics"

heading_anchors: true

render_with_liquid: false

# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

include:
  - figures
  - figures/environments.png
  - docs/assets/vscode/*.png

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"]

# Links that appear in the top right corner of the webpage
aux_links:
  "PICSciE Knowledge Base":
    - "https://researchcomputing.princeton.edu/support/knowledge-base"
  "University Webpage":
    - "https://geosciences.princeton.edu/research/geophysics"


# Footer metadata
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Github Stuff
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/princeton-geophysics/princeton-geophysics" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree"


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# readme_index:
#   enabled:          true
#   remove_originals: false
#   with_frontmatter: false

# Colors
# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"
